import React,{useEffect,useMemo,useState} from 'react';
import{Atom,ArrowLeft,ArrowRight,Check,ChevronRight,CircleHelp,CloudSun,FlaskConical,Leaf,Maximize2,Minimize2,Pause,Play,RotateCcw,Scale,Sparkles,Sun,Volume2,VolumeX,Wind,Zap,Droplets}from'lucide-react';

type Tab='home'|'model'|'light'|'calvin'|'compare'|'quiz';
const tabs:{id:Tab;label:string;short:string}[]=[
{id:'home',label:'Başlangıç',short:'01'},{id:'model',label:'Büyük Model',short:'02'},{id:'light',label:'Işığa Bağlı',short:'03'},{id:'calvin',label:'Calvin Döngüsü',short:'04'},{id:'compare',label:'Karşılaştır',short:'05'},{id:'quiz',label:'Soru-Cevap',short:'06'}];

const speakText=(text:string,enabled:boolean)=>{if(!enabled||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='tr-TR';u.rate=.84;u.pitch=1;window.speechSynthesis.speak(u)};

export default function App(){
 const[tab,setTab]=useState<Tab>('home');const[sound,setSound]=useState(true);const[full,setFull]=useState(false);
 useEffect(()=>{const f=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>document.removeEventListener('fullscreenchange',f)},[]);
 const go=(t:Tab)=>{window.speechSynthesis?.cancel();setTab(t)};
 const toggleSound=()=>setSound(v=>{if(v&&window.speechSynthesis)window.speechSynthesis.cancel();return!v});
 const toggleFull=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>{});
 return <div className="bio-app">
  <header className="bio-header">
   <button className="bio-logo" onClick={()=>go('home')}><span><Leaf/></span><div><b>PHOTOSYNTHESIS</b><small>10. SINIF · ETKİLEŞİMLİ MODEL</small></div></button>
   <nav>{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>go(t.id)}><i>{t.short}</i>{t.label}</button>)}</nav>
   <div className="header-tools"><button onClick={toggleSound}>{sound?<Volume2/>:<VolumeX/>}</button><button onClick={toggleFull}>{full?<Minimize2/>:<Maximize2/>}</button></div>
  </header>
  <main className="bio-main">
   {tab==='home'&&<Home onStart={()=>go('model')} speak={(x)=>speakText(x,sound)}/>}
   {tab==='model'&&<Model onNext={()=>go('light')} speak={(x)=>speakText(x,sound)}/>}
   {tab==='light'&&<Light onNext={()=>go('calvin')} speak={(x)=>speakText(x,sound)}/>}
   {tab==='calvin'&&<Calvin onNext={()=>go('compare')} speak={(x)=>speakText(x,sound)}/>}
   {tab==='compare'&&<Compare onNext={()=>go('quiz')} speak={(x)=>speakText(x,sound)}/>}
   {tab==='quiz'&&<Quiz speak={(x)=>speakText(x,sound)}/>}
  </main>
  <footer><span>FOTOSENTEZ · BİLİMSEL MODEL</span><span>{tabs.findIndex(t=>t.id===tab)+1} / {tabs.length}</span><button onClick={()=>go(tabs[Math.max(0,tabs.findIndex(t=>t.id===tab)-1)].id)}><ArrowLeft/></button><button onClick={()=>go(tabs[Math.min(tabs.length-1,tabs.findIndex(t=>t.id===tab)+1)].id)}><ArrowRight/></button></footer>
 </div>
}

function Title({eyebrow,title,desc,speak}:{eyebrow:string;title:React.ReactNode;desc:string;speak:()=>void}){return <div className="title-row"><div><span>{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div><button className="speak-btn" onClick={speak}><Volume2/> ANLAT</button></div>}

function Home({onStart,speak}:{onStart:()=>void;speak:(x:string)=>void}){return <section className="home">
 <div className="home-copy"><span className="eyebrow">10. SINIF · BİYOLOJİ</span><h1>Fotosentezi<br/><em>çalıştır.</em></h1><p>Fotosentez reaksiyonlarını bir şema olarak değil, <b>madde ve enerji akışı</b> olarak keşfet.</p><div className="home-actions"><button onClick={onStart}>MODELİ BAŞLAT <ArrowRight/></button><button className="ghost" onClick={()=>speak('Fotosentezde ışık enerjisi, su ve karbondioksit kullanılır. Işığa bağlı tepkimelerde ATP ve NADPH oluşur; Calvin döngüsünde bu moleküller kullanılarak organik madde sentezlenir.') }><Volume2/> KISA ANLAT</button></div><div className="home-facts"><span><Sun/> Işık</span><span><Droplets/> H₂O</span><span><Wind/> CO₂</span><span><Zap/> ATP + NADPH</span></div></div>
 <div className="hero-art"><div className="hero-glow"/><div className="hero-leaf"><svg viewBox="0 0 520 430"><defs><radialGradient id="g"><stop stopColor="#d9f99d"/><stop offset="1" stopColor="#65a30d"/></radialGradient></defs><path d="M260 390C95 335 55 170 185 55c83-73 190-47 253 5 43 35 35 110-4 164-52 72-112 123-174 166Z" fill="url(#g)" opacity=".92"/><path d="M257 382C264 265 278 176 420 72M260 380C203 300 150 246 101 219" stroke="#f4ffd9" strokeWidth="5" fill="none" opacity=".55"/><g fill="#f8ffd9" opacity=".9"><circle cx="330" cy="130" r="5"/><circle cx="365" cy="164" r="4"/><circle cx="294" cy="205" r="4"/></g></svg></div><div className="hero-orbit orbit1">CO₂</div><div className="hero-orbit orbit2">O₂</div><div className="hero-orbit orbit3">ATP</div><div className="hero-orbit orbit4">NADPH</div><div className="hero-caption">KLOROPLAST<br/><small>ENERJİ → MADDE</small></div></div>
 </section>}

function Model({onNext,speak}:{onNext:()=>void;speak:(x:string)=>void}){return <section className="page"><Title eyebrow="02 · BÜYÜK RESİM" title={<>Fotosentezin <em>motorunu</em> gör.</>} desc="İki ana süreç birbirinden kopuk değildir. Işığa bağlı tepkimeler ATP ve NADPH üretir; Calvin döngüsü bunları kullanır." speak={()=>speak('Fotosentez iki ana bölümden oluşur. Işığa bağlı tepkimelerde pigmentler ışığı soğurur, su parçalanır, elektronlar ETS boyunca taşınır ve ATP ile NADPH oluşur. Calvin döngüsünde CO₂, ATP ve NADPH kullanılarak organik madde sentezine giden ürünler oluşur.')}/>
 <div className="model-map">
  <div className="input-rail"><Node icon={<Sun/>} title="IŞIK" sub="enerji" gold/><Node icon={<Droplets/>} title="H₂O" sub="elektron kaynağı"/><Node icon={<Wind/>} title="CO₂" sub="karbon kaynağı"/></div>
  <div className="chloroplast-map"><div className="zone-label">KLOROPLAST</div><div className="thylakoid-zone"><h3><Sun/> IŞIĞA BAĞLI TEPKİMELER</h3><div className="chain"><b>Pigment</b><i>→</i><b>ETS</b><i>→</i><strong>ATP</strong><strong>NADPH</strong></div><small>H₂O → O₂ + e⁻ · Tilakoit zarı</small></div><div className="energy-bridge"><span>ATP + NADPH</span><ArrowRight/></div><div className="stroma-zone"><h3><Leaf/> CALVİN DÖNGÜSÜ</h3><div className="formula"><b>CO₂</b><i>+</i><b>ATP</b><i>+</i><b>NADPH</b><i>→</i><strong>ORGANİK MADDE SENTEZİ</strong></div><small>Stroma · ışık doğrudan kullanılmaz</small></div></div>
  <div className="output-rail"><Node title="O₂" sub="ortama verilir" blue/><Node title="ORGANİK MADDE" sub="sentezlenir" green/></div>
 </div><div className="bottom-callout"><span><Sparkles/> <b>Sunum ipucu:</b> “Soldan girenler → içerideki dönüşüm → sağdaki ürünler.”</span><button onClick={onNext}>IŞIK REAKSİYONLARINI AÇ <ArrowRight/></button></div>
 </section>}

function Node({icon,title,sub,gold,green,blue}:{icon?:React.ReactNode;title:string;sub:string;gold?:boolean;green?:boolean;blue?:boolean}){return <div className={'node '+(gold?'gold ':'')+(green?'green ':'')+(blue?'blue':'')}>{icon&&<span>{icon}</span>}<b>{title}</b><small>{sub}</small></div>}

function Light({onNext,speak}:{onNext:()=>void;speak:(x:string)=>void}){const[step,setStep]=useState(0);const[auto,setAuto]=useState(false);const stages=[['Pigment ışığı soğurur','Pigmentler foton enerjisini soğurur ve reaksiyon merkezindeki elektronları uyarır.','FOTON → e⁻'],['Su parçalanır','Suyun fotoliziyle elektronlar sisteme katılır; O₂ yan ürün olarak açığa çıkar.','H₂O → 2H⁺ + 2e⁻ + ½O₂'],['Elektronlar ETS’de taşınır','Elektron akışı, protonların lümende birikmesine katkı sağlayan enerji akışını oluşturur.','e⁻ → ETS → H⁺'],['ATP sentezlenir','H⁺ iyonları ATP sentazdan geçerken ATP sentezlenir.','ADP + Pi → ATP'],['NADPH oluşur','Elektronlar ve H⁺, NADP⁺’nin NADPH’ye indirgenmesinde kullanılır.','NADP⁺ → NADPH']];useEffect(()=>{if(!auto)return;const t=setInterval(()=>setStep(s=>{if(s===4){setAuto(false);return 4}return s+1}),1800);return()=>clearInterval(t)},[auto]);return <section className="page"><Title eyebrow="03 · IŞIĞA BAĞLI TEPKİMELER" title={<>Enerjinin <em>yolculuğunu</em> izle.</>} desc="Her adımı dokunarak seç. Animasyon, biyolojik olayın neden-sonuç ilişkisini vurgular." speak={()=>speak('Işığa bağlı tepkimelerde pigmentler ışığı soğurur. Su parçalanır, elektronlar ETS boyunca taşınır, proton gradyanı oluşur, ATP sentaz ATP üretir ve NADPH oluşur.')}/>
 <div className="light-lab"><div className="lab-side"><div className="big-sun"><Sun/></div><Node title="H₂O" sub="fotoliz" icon={<Droplets/>}/><div className="side-arrow">↓</div><Node title="O₂" sub="yan ürün" blue/></div>
 <div className="membrane-scene"><div className="scene-label">TİLAKOİT ZARI</div><div className="stroma">STROMA</div><div className="lumen">LÜMEN · H⁺</div><div className="membrane-band"/><div className={'complex pigment '+(step>=0?'on':'')}><span>PIGMENT</span></div><div className={'complex ets '+(step>=2?'on':'')}><span>ETS</span></div><div className={'complex atps '+(step>=3?'on':'')}><span>ATP<br/>SENTAZ</span></div><div className="particles">{Array.from({length:7},(_,i)=><i key={i} className={step>=2?'fly':''}>e⁻</i>)}</div><div className="protons">{Array.from({length:8},(_,i)=><i key={i} className={step>=2?'rise':''}>H⁺</i>)}</div><div className={'product p-atp '+(step>=3?'show':'')}>ATP</div><div className={'product p-nadph '+(step>=4?'show':'')}>NADPH</div></div>
 <div className="step-card"><span>ADIM {step+1} / 5</span><h2>{stages[step][0]}</h2><p>{stages[step][1]}</p><strong>{stages[step][2]}</strong><div className="step-list">{stages.map((x,i)=><button key={i} className={i===step?'active':''} onClick={()=>{setAuto(false);setStep(i)}}><i>{i+1}</i>{x[0]}</button>)}</div></div></div>
 <div className="control-bar"><button onClick={()=>{setAuto(false);setStep(Math.max(0,step-1))}}><ArrowLeft/></button><button className="play" onClick={()=>setAuto(!auto)}>{auto?<Pause/>:<Play/>}{auto?' DURDUR':' OTOMATİK GÖSTER'}</button><button onClick={()=>{setAuto(false);setStep(Math.min(4,step+1))}}><ArrowRight/></button><button onClick={()=>{setAuto(false);setStep(0)}}><RotateCcw/></button><button className="next" onClick={onNext}>CALVİN DÖNGÜSÜ <ArrowRight/></button></div>
 </section>}

function Calvin({onNext,speak}:{onNext:()=>void;speak:(x:string)=>void}){const[phase,setPhase]=useState(0);const phases=[['1','CO₂ girişi','Karbon kaynağı döngüye katılır.'],['2','Karbon işlenir','ATP enerji, NADPH ise indirgeme gücü sağlar.'],['3','Organik ürünler','G3P gibi üç karbonlu ürünler oluşur.'],['4','Yenilenme','Döngünün devamı için başlangıç maddelerinin bir bölümü yenilenir.']];useEffect(()=>{const t=setInterval(()=>setPhase(p=>(p+1)%4),3500);return()=>clearInterval(t)},[]);return <section className="page"><Title eyebrow="04 · CALVİN DÖNGÜSÜ" title={<>Karbonun <em>hikâyesi.</em></>} desc="Işık doğrudan burada kullanılmaz. Işığa bağlı tepkimelerden gelen ATP ve NADPH, CO₂'nin organik madde sentezine giden yolda işlenmesine yardımcı olur." speak={()=>speak('Calvin döngüsünde CO₂ karbon kaynağıdır. ATP enerji sağlar, NADPH indirgeme gücü sağlar. Döngünün ürünlerinden G3P organik madde ve karbonhidrat sentezinde kullanılabilir; bir bölümü döngünün yenilenmesi için kullanılır.')}/>
 <div className="calvin-lab"><div className="calvin-input"><Node title="CO₂" sub="karbon kaynağı" gold/><div className="energy-pipe"><Zap/><b>ATP + NADPH</b><small>ışığa bağlı tepkimelerden</small></div></div><div className="cycle-visual"><div className="orbit"><span/><span/><span/><span/><span/><span/></div><div className="cycle-core"><Leaf/><b>CALVİN<br/>DÖNGÜSÜ</b><small>STROMA</small></div><div className="particle co2">CO₂</div><div className="particle atp">ATP</div><div className="particle nad">NADPH</div></div><div className="calvin-output"><Node title="G3P" sub="organik ürün" green/><div className="fact-box"><Check/> Bir bölüm döngünün yenilenmesine, bir bölüm karbonhidrat sentezine gidebilir.</div></div></div>
 <div className="phase-strip">{phases.map((p,i)=><button className={i===phase?'active':''} onClick={()=>setPhase(i)} key={i}><i>{p[0]}</i><div><b>{p[1]}</b><small>{p[2]}</small></div></button>)}</div><div className="bottom-callout"><span><Scale/> <b>Önemli ayrım:</b> Calvin döngüsü ışığı doğrudan kullanmaz; ATP ve NADPH kullanır.</span><button onClick={onNext}>MODELİ KARŞILAŞTIR <ArrowRight/></button></div>
 </section>}

function Compare({onNext,speak}:{onNext:()=>void;speak:(x:string)=>void}){return <section className="page"><Title eyebrow="05 · ÖDEV BASAMAĞI 7–9" title={<>Modelini <em>bilimsel modelle</em> karşılaştır.</>} desc="Bu ekran, yönergedeki karşılaştırma ve modelini yenileme basamaklarını görünür hâle getirir." speak={()=>speak('Modelimi bilimsel modelle karşılaştırırken pigmentlerin ışığı soğurması, suyun parçalanması, ETS, ATP sentezi, NADPH oluşumu ve Calvin döngüsünde ATP ile NADPH kullanılması gibi temel ilişkileri kontrol ederim.')}/>
 <div className="compare-grid"><div className="compare-card mine"><span>BENİM MODELİM</span><h2>İnteraktif model</h2><ul><li><Check/> Pigmentlerin rolü</li><li><Check/> H₂O fotolizi ve O₂</li><li><Check/> ETS ve proton gradyanı</li><li><Check/> ATP + NADPH → Calvin</li><li><Check/> CO₂ → organik ürünler</li></ul></div><div className="vs">VS</div><div className="compare-card science"><span>BİLİMSEL MODELDE KONTROL</span><h2>Kanıt kontrol listesi</h2><div className="check-row"><b>✓</b><span>Işığa bağlı tepkimeler</span><small>Tilakoit zarı</small></div><div className="check-row"><b>✓</b><span>Calvin döngüsü</span><small>Stroma</small></div><div className="check-row"><b>✓</b><span>ATP / NADPH bağlantısı</span><small>İki süreç arasında madde akışı</small></div><div className="check-row"><b>✓</b><span>Pigment görevi</span><small>Işık enerjisinin soğurulması</small></div></div></div>
 <div className="revision"><div><span>MODELİ YENİLE</span><b>Eksik / hatalı / geliştirilecek yönü seç:</b></div><div className="revision-tags"><button>ATP–Calvin bağlantısını güçlendir</button><button>Pigmentleri açıkla</button><button>O₂'nin kaynağını düzelt</button><button>G3P → karbonhidrat ilişkisini göster</button></div><div className="revision-result"><Sparkles/><span><b>Revize model:</b> Fotosentez artık iki ayrı kutu değil, ATP ve NADPH aracılığıyla bağlı tek bir sistem olarak gösteriliyor.</span></div></div>
 <div className="bottom-callout"><span><FlaskConical/> <b>Son basamak:</b> Revize ettiğin modeli sınıfta açıklayabilirsin.</span><button onClick={onNext}>SORU-CEVAP'A GEÇ <ArrowRight/></button></div>
 </section>}

function Quiz({speak}:{speak:(x:string)=>void}){const qs=[['Fotosentezde atmosfere verilen O₂’nin kaynağı nedir?',['CO₂','H₂O','ATP'],'H₂O'],['ATP sentezinde H⁺ iyonları hangi yapıdan geçer?',['Rubisco','ATP sentaz','Klorofil'],'ATP sentaz'],['Calvin döngüsünde doğrudan kullanılan enerji taşıyıcıları hangileridir?',['ATP ve NADPH','O₂ ve H₂O','CO₂ ve O₂'],'ATP ve NADPH'],['Pigmentlerin temel görevi nedir?',['Işığı soğurmak','CO₂ üretmek','Glikozu parçalamak'],'Işığı soğurmak'],['CO₂ fotosentezin hangi ana bölümünde kullanılır?',['Işığa bağlı tepkimeler','Calvin döngüsü','Suyun fotolizi'],'Calvin döngüsü']];const[i,setI]=useState(0);const[answer,setAnswer]=useState<string|null>(null);const[score,setScore]=useState(0);const q=qs[i];const choose=(a:string)=>{if(answer)return;setAnswer(a);if(a===q[2])setScore(s=>s+1)};const next=()=>{setAnswer(null);setI(x=>Math.min(qs.length-1,x+1))};return <section className="quiz-page"><div className="quiz-head"><span>06 · SORU-CEVAP</span><h1>Şimdi modeli <em>sen anlat.</em></h1><p>Sunumun sonunda sınıfa soru sorabilir veya kendini test edebilirsin.</p></div><div className="quiz-card"><div className="quiz-number">{String(i+1).padStart(2,'0')} / {qs.length}</div><CircleHelp/><h2>{q[0]}</h2><div className="answers">{q[1].map(a=><button key={a} className={answer?(a===q[2]?'correct':a===answer?'wrong':'dim') :''} onClick={()=>choose(a)}><span>{String.fromCharCode(65+q[1].indexOf(a))}</span>{a}</button>)}</div>{answer&&<div className={'answer-note '+(answer===q[2]?'good':'bad')}>{answer===q[2]?<><Check/> Doğru! Modeldeki ilişkiyi yakaladın.</>:<>Yanlış. Doğru cevap: <b>{q[2]}</b></>}</div>}</div><div className="quiz-footer"><span>PUAN <b>{score} / {i+(answer?1:0)}</b></span>{i<qs.length-1?<button onClick={next} disabled={!answer}>SONRAKİ SORU <ArrowRight/></button>:<button onClick={()=>{setI(0);setAnswer(null);setScore(0)}}><RotateCcw/> YENİDEN</button>}</div></section>}
